const AppConstant = {
    CREATE_USER : 'CREATE_USER',
    VIEW_NOTIFICATION:'VIEW_NOTIFICATION',
    VIEW_EMPLOYEE: 'VIEW_EMPLOYEE',

    ATTENDANCE_ALL: 'ATTENDANCE_ALL',
    ATTENDANCE_SINGLE: 'ATTENDANCE_SINGLE',
    CREATE_VISITOR: 'CREATE_VISITOR',
    VIEW_VISITOR: 'VIEW_VISITOR',


}

export default  AppConstant;