const AppConstant = {
    CREATE_USER : 'CREATE_USER',
    VIEW_NOTIFICATION:'VIEW_NOTIFICATION',
    VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
    VIEW_EMPLOYEE: 'VIEW_EMPLOYEE'
}

export default  AppConstant;